### ISSUE TITLE
Will the ABP credentials expire(dev_addr etc)?

### ISSUE THREAD

**Issue by MedadRufus** [ImperialSpaceSociety/LoRaMac-node#214]
Find out out the mechanism for the end node to detect server network change. its a mac command periodically sent

**Comment by MedadRufus** [comment]
Its quite unlikely that it will expire. But as a plan b, consider sending a special downlink to tracker to update the keys. This can be done via either the TTN or Helium network. Hopefully keys on both networks don't expire at the same time.

**Comment by MedadRufus** [comment]
I have thought about the credentials expiring problem. I don't think it will for a very long time. Or else, many devices will simply become bricks as they won't know that the credentials are expired, and will tx on the expired ones.

**Comment by MedadRufus** [comment]
In theory, the OTAA end device is meant to periodically send a LinkCheckReq to check if its connected to the network. If no response(LinkCheckAns) from server(via a downlink), it is meant to join again. This is simply not going to work on the balloon tracker, as its going to spend most of its flight out of range. Then it will keep trying to join. I don't want it to do many joins!(or any at all!) as it requires a downlink.

Read more about this strategy of making joins when no response is found in the semtech app note:
https://lora-developers.semtech.com/documentation/tech-papers-and-guides/the-book/joining-and-rejoining

As of now, this logic of doing a join if no ack is received is not implemented in the LoRaMac-node reference code,

**Comment by MedadRufus** [comment]
The things network recommends doing an OTAA join in the factory, then persist all the keys for the lifetime of the device, suggesting that it will not ever expire.

Read it in the white paper: https://www.thethingsindustries.com/docs/devices/abp-vs-otaa/

**Comment by MedadRufus** [comment]
I am hoping the same logic can be used on the helium network. I am hoping the session keys(`DevAddr`, `NwkSKey` and `AppSKey`) will be persisted on the server side for a long time(at least 1 year).

**Comment by pimente** [comment]
Maybe we could ask the guys from Helium referring TTN's white paper above?

**Comment by MedadRufus** [comment]
The question to ask is: What is the lifetime of the session keys(`DevAddr`, `NwkSKey` and `AppSKey`)? As a first step, we can look at the source code for the helium network, which is Open Source. Things to spot are if there is expiry logic in there. I highly doubt there is.

**Comment by MedadRufus** [comment]
There is some info from the TTN people on the [TTN forumn](https://www.thethingsnetwork.org/forum/t/how-often-should-a-node-do-an-otaa-join-and-is-otaa-better-than-abp/11192). They say they have a robust backup system. 


> @htdvisser 12:02 PM
>
> As you may know, we use Redis, an in-memory data store to store devices. This gives us very high performance (messages being handled in a couple of µs), but indeed has a higher risk of data loss. Redis has two mechanisms for persistence, and we use both of them. The first is to write every transaction to an append-only file, which, in case of a power outage, we can replay to restore the state. In the worst case, we may lose the last transaction if the disk write was interrupted. The second mechanism is to make periodic dumps of the entire data store. The dump frequency depends on the number of writes, but it happens at least every 10 minutes. This dump can be used if, for some reason, the first mechanism fails.
>
>
>
> Next to this, we have an off-site storage facility where we keep hourly, daily and weekly backups of those dump files, plus all configuration files that are needed to fully restore the server to the exact state at that point in time. These backups should only be needed if the server’s SSD can not be recovered for some reason.


So it can be assumed that on the Things Network at least, the join session keys(`DevAddr`, `NwkSKey` and `AppSKey`) will never expire. Now the question is: will it expire on the Helium network?

Just to be safe, I think consider using this method:


> Its quite unlikely that it will expire. But as a plan b, consider sending a special downlink to tracker to update the keys. This can be done via either the TTN or Helium network. Hopefully keys on both networks don't expire at the same time.

**Comment by pimente** [comment]
I don't think data loss and back up is the problem/solution we should be concerned about here.
I am more worried by the fact that they could have intentionally set up expiration for those credentials. Back up will only prevent from unintentional deletion. Since I have never seen any advice to reuse credentials, at some point there will be collisions if they don't have an expiration mechanism. The number of `DevAddr` is necessarily finite and after a finite number of join requests, they will eventually be depleted.
That being said, I've not done the math, so that could be in several years and if so, maybe there is no expiration mechanism yet in place or a very long expiration duration.

I think a simple way to have a minimum bound is to wait... and test. My first credentials are already 1 week old and in 3 weeks I can test if they will last at least 1 month. There will be many other ways for a pico balloon to fail in one month than credentials expiration... Do you have older valid credentials?

I think your method is also an option but imagine you've not heard the balloon for the last 10 days, will you be willing to try to reset credentials not knowing where the balloon is? If that does not work you will never know if it did not because of uplink not being received, network coverage, software bug... I would feel much more at rest if we had a minimum bound on these credentials life time 😉

**Comment by htdvisser** [comment]
Hi guys,

No worries.

The Things Network still does backups, so if our database servers burn down, we can restore them from those backups.

The Things Network doesn't have an expiration time on sessions, and if we would decide to add expiration in the future, it would definitely be after _at least_ a year of inactivity.

You can of course also just keep track of your DevEUIs, AppKeys, DevAddrs, NwkSKeys, AppSKeys, etc. yourself. That way you can always re-register your device on The Things Network (or any other LoRaWAN network) if you accidentally delete it.

Good luck with your project!

**Comment by pimente** [comment]
Thank you @htdvisser for your work on TTN and this clarification.
That ends up a lot of speculation 😄 
Now, let's focus on flying these things.

**Comment by MedadRufus** [comment]
The ability to change the keys with a special downlink I think mitigates the impact of this problem. The new keys can be sent up via either network: The Things Network or the Helium Network. So if the keys expire on one network, the keys can be sent up via the other network. 
This feature has been implemented in #250

**Comment by MedadRufus** [comment]
After some long term testing, I have discovered that after around 2 weeks of inactivity, Helium network session keys become invalid; I have to rejoin to get new session keys. Major issue. This is not an issue on The Things Network.

@pimente have you run into this issue?

**Comment by MedadRufus** [comment]
The issue appears intermittent though. In my implementation, I cycle through 10 device registration credentials, but I discovered that packets sent on credentials from one of the devices would not appear on console. All other 9 device registrations work.

![image](https://user-images.githubusercontent.com/26815217/146090202-4a0211ea-21e6-4505-adfa-4bbc6578d1dd.png)

**Comment by MedadRufus** [comment]
I am not sure if there is an expiration date built into the ABP credentials.

**Comment by pimente** [comment]
I have not done extensive tests because my reception on the Helium network on the ground is not very reliable.

I have sent a balloon on the Helium network with intermediate success because the Helium network [crashed](https://status.helium.com/incidents/zl82xrgl9p30) in the middle of the flight. The balloon disappeared after 6 days. I don't know why. Probably icing or maybe expired credentials...

According to your observations, does it expire after ~2 weeks of inactivity or two weeks on the ABP credentials? 
If it is after 2 weeks of inactivity, an easy workaround would be to send a dummy packet from the ground once every week from the same credentials to make sure they don't expire.

**Comment by MedadRufus** [comment]
> According to your observations, does it expire after ~2 weeks of inactivity or two weeks on the ABP credentials?

It happens after 2 weeks of inactivity. If it continuously transmits every few minutes, there is no issue.

I do like the workaround of sending a dummy packet.
